id: P000391
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:31.887678
source_metadata:
  id: bdr:W1KG15937
  title: དབུ་མའི་སྤྱི་དོན་སྐལ་བཟང་མགུལ་རྒྱན།
  author: ''
  volumes:
    d603c9700ad347a7b1a0717040781c56:
      image_group_id: I1KG15948
      title: Volume 1 of dbu ma'i spyi don skal bzang mgul rgyan/
      volume_number: 1
      total_pages: 372
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
